"""
Utility functions for the Generalized DPRF framework.
"""

import os
import json
from typing import Dict, List, Any, Optional, Union


def load_json(file_path: str) -> Dict[str, Any]:
    """
    Load a JSON file and return its contents as a dictionary.
    
    Args:
        file_path: Path to the JSON file
        
    Returns:
        Dictionary containing the JSON contents
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_json(data: Dict[str, Any], file_path: str) -> None:
    """
    Save a dictionary as a JSON file.
    
    Args:
        data: Dictionary to save
        file_path: Path where the JSON file will be saved
    """
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def ensure_directory(directory_path: str) -> None:
    """
    Ensure that a directory exists, creating it if necessary.
    
    Args:
        directory_path: Path to the directory
    """
    os.makedirs(directory_path, exist_ok=True)


def format_persona_prompt(persona: str, content: str, instruction: str) -> str:
    """
    Format the prompt for the persona-based task.
    
    Args:
        persona: Description of the persona
        content: Text content to process
        instruction: Task instruction
        
    Returns:
        Formatted prompt for the model
    """
    return f"""You are embodying the following persona:

{persona}

Please perform the following task based on the provided content, while staying true to your persona.

CONTENT:
{content}

INSTRUCTION:
{instruction}

Your response:"""


def format_analysis_prompt(
    persona: str, 
    content: str, 
    generated_response: str, 
    ground_truth: str
) -> str:
    """
    Format the prompt for the first step of persona refinement: analyzing differences.
    
    Args:
        persona: Current description of the persona
        content: Text content processed
        instruction: Task instruction
        generated_response: Response generated by the agent
        ground_truth: Ground truth response
        
    Returns:
        Formatted prompt for the analysis model
    """
    return f"""I need to analyze the differences between a response generated using a specific persona and a ground truth response.

PERSONA DESCRIPTION:
{persona}

CONTENT:
{content}

GENERATED RESPONSE (using the persona):
{generated_response}

GROUND TRUTH RESPONSE (desired response):
{ground_truth}

Please provide a detailed analysis of the differences between the generated response and the ground truth response. 
Focus on identifying:
1. Specific viewpoints, perspectives, or stances that the persona is missing
2. Reasoning patterns or analytical frameworks that differ
3. Areas where the persona's knowledge or expertise seems insufficient
4. Tonal or stylistic differences that impact the effectiveness
5. Structural elements or organization that differ significantly

Your analysis should be thorough and identify specific examples from both responses.
"""


def format_refinement_prompt(
    persona: str, 
    analysis: str
) -> str:
    """
    Format the prompt for the second step of persona refinement: refining the persona.
    
    Args:
        persona: Current description of the persona
        analysis: Analysis of differences between responses
        
    Returns:
        Formatted prompt for the refinement model
    """
    return f"""I'm trying to refine a persona description for an AI model based on an analysis of where its current responses differ from desired responses.

CURRENT PERSONA DESCRIPTION:
{persona}

ANALYSIS OF DIFFERENCES:
{analysis}

Please create a refined version of the persona description that addresses the issues identified in the analysis. 
The refined persona should:
1. Maintain the core identity and role of the original persona
2. Add specific expertise, viewpoints, and reasoning patterns that were missing
3. Modify any problematic aspects identified in the analysis
4. Be specific and detailed enough to guide an AI's responses effectively
5. Be concise and well-structured

Format your response as:
REFINED PERSONA: [The updated persona description]
"""


def format_peer_review_instruction() -> str:
    """
    Returns a standardized instruction for the peer review task.
    
    Returns:
        Instruction for peer review
    """
    return """Please provide a comprehensive scientific peer review of this paper. 
Your review should:
1. Summarize the main contributions and findings
2. Evaluate the scientific merit and methodological rigor
3. Identify strengths and weaknesses in the approach, experiments, and analysis
4. Assess the clarity, organization, and presentation of the work
5. Suggest specific areas for improvement
6. Provide an overall recommendation (Accept/Minor Revision/Major Revision/Reject)

Base your assessment on scientific standards for research papers, considering originality, significance, validity, and clarity.""" 